// outline() emits reusable Acus functions instead of inlining the algorithms
// at every call site.

using NameString = String<20>;
auto read_line = io::read_line<NameString>.outline();
auto strlen = NameString::length.outline();

function_<void()>("main") | define {
  print("What is your name? ");
  auto name = read_line();

  print("Hello, ");
  println(name);

  print("Your name has ");
  print(strlen(name));
  println(" characters.");

  return_;
};
